/*

LEVEL AUTO GENERRATOR                                   -COMPLETE
ADD PADDLE SMOTHNESS                                    -COMPLETE
PADDLE WITH MOUSE MOVEMENT                              -COMPLETE
LOAD BLCOK FROM PROGRESSION TO NEW MECHANICS            -COMPLETE
ADJUST COLLISION PARTICLE TO BURST                      -COMPLETE
ADJUST LVL BLOCK PERCENTAGES BASE ON PROGRESSION        -COMPLETE
FIX BALL GETTING SLOWER                                 -COMPLETE     
FIX SPRITE LAYER ORDER                                  -COMPLETE
INCREASE BALL SPEED WITH PROGRESSION                    -COMPLETE                          
ADAPT GAME SESSION TRACKER TO SINGLE SCENE MECHANICS    -COMPLETE
CREATE A SESSION MANAGER THAT HOLDS THE LVL             -COMPLETE
FIX BALLS AND BLOCKS TO GET LVL FROM MANAGER            -COMPLETE
RESET BALL WHEN GETTING TO A NEW LEVEL                  -COMPLETE
GIVE THE PLAYER LIFES                                   -COMPLETE
CREATE A SCENE MANAGER                                  -COMPLETE
ADD DIFFERENT AUDIO SOUNDS TO BALL CRASHING             
ANIMATE TITLE AND GAMEOVER TEXT                         -COMPLETE
CREATE ASYNCRONUS ANIMATIONS TO PLAY BETWEEN SCENES     
CREATE ABOUT 10 PROGRESSIONS                            
ADAPT PADDLE TO BE ON THE FINGER POSITION FOR MOBILE    
PREVENT UNBREAKABLE TO APPEAR 38 BLOCKS FROM EACHOTHER  

 */